import Alerta from './alerta';
import Cabecera from './cabecera';
import Paginacion from './paginacion';
import ComunaSelect from './comuna-select';
import IngresarDireccion from './ingresar-direccion';
import MateriaCheckBoxGroup from './materia-check-box-group';
import TipoPersonaSelect from './tipo-persona-select';
import MateriaSelect from './materia-select';
import TipoDireccionSelect from './tipo-direccion-select';
export {Alerta, Cabecera, Paginacion, ComunaSelect, IngresarDireccion, MateriaCheckBoxGroup, TipoPersonaSelect, MateriaSelect, TipoDireccionSelect};
